name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  IMAGE_NAME: wisecow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Export image tag
        id: meta
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'
        if: ${{ env.KUBECONFIG_B64 != '' }}

      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        if: ${{ env.KUBECONFIG_B64 != '' }}

      - name: Replace image placeholder in manifests
        run: |
          sed -i "s#DOCKERHUB_USERNAME/wisecow:latest#${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${{ github.sha }}#g" k8s/deployment.yaml
        if: ${{ env.KUBECONFIG_B64 != '' }}

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml
          # Ingress is optional; will work if controller + cert-manager installed
          if [ -f k8s/ingress.yaml ]; then kubectl apply -f k8s/ingress.yaml || true; fi
        if: ${{ env.KUBECONFIG_B64 != '' }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deploy/wisecow-deployment --timeout=120s
        if: ${{ env.KUBECONFIG_B64 != '' }}

